# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Security-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
      
    name: Credo Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.17.5
      with:
        elixir-version: '1.15.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version
    - name: Install dependencies
      run: mix deps.get
    - name: compile dependencies
      run: mix deps.compile
    - name: compile
      run: mix compile
    - name: credo-scan
      run: mix credo --format=sarif | tee credo_output.sarif
      
    - name: upload sarif
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: false
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: credo_output.sarif
        token: ${{ secrets.GITHUB_TOKEN }}